[package]
name = "fpm"
version = "0.1.2"
authors = ["Amit Upadhyay <upadhyay@gmail.com>", "Shobhit Sharma <shobhit@fifthtry.com>"]
edition = "2021"
description = "fpm: FTD Package Manager"
license = "MIT"
repository = "https://github.com/FifthTry/fpm"
homepage = "https://fpm.dev"


[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ftd = { version = "0.1.11", path = "../ftd" }
clap = "2.33.3"
home = "0.5.3"
reqwest = { version = "0.11.6"}
tokio = { version = "1.14.0", features = ["full"] }

[dev-dependencies]
rusty-hook = "^0.11.2"
fbt-lib = { version = "0.1.12", path = "../fbt/fbt_lib" }
