[package]
name = "fpm"
version = "0.1.4"
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Shobhit Sharma <shobhit@fifthtry.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
]
edition = "2021"
description = "fpm: FTD Package Manager"
license = "MIT"
repository = "https://github.com/FifthTry/fpm"
homepage = "https://fpm.dev"


[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ftd = "0.1.15"
clap = "2.33.3"
home = "0.5.3"
reqwest = "0.11.6"
tokio = { version = "1.14.0", features = ["full"] }
futures = "0.3.18"
zip = "0.5"
thiserror = "1.0"
serde_derive = "1.0"
url = "2.2.2"
async-recursion = "0.3.2"
diffy = "0.2.1"
ignore = "0.4.18"
rusqlite = "0.26.1"
indoc = "1.0"

[dev-dependencies]
rusty-hook = "^0.11.2"
fbt-lib = "0.1.14"
indoc = "1"
pretty_assertions = "1"
