[package]
name = "fpm"
version = "0.1.9"
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Shobhit Sharma <shobhit@fifthtry.com>",
]
edition = "2018"
description = "fpm: FTD Package Manager"
license = "MIT"
repository = "https://github.com/FifthTry/fpm"
homepage = "https://fpm.dev"


[dependencies]
async-recursion = "0.3.2"
camino = "1.0.5"
clap = "2.33.3"
diffy = "0.2.1"
ftd = "0.1.17"
futures = "0.3"
home = "0.5.3"
ignore = "0.4.18"
indoc = "1.0"
reqwest = "0.11.6"
rusqlite = { version = "0.26.3", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1"
thiserror = "1.0"
tokio = { version = "1.14.0", features = ["full"] }
url = "2.2.2"
zip = "0.5"
termcolor = "1.1.2"
regex = "1.1.9"
chrono = "0.4.19"

[dev-dependencies]
fbt-lib = "0.1.16"
indoc = "1"
pretty_assertions = "1"
rusty-hook = "^0.11.2"
