name: Build release

on:
  push:
    branches: [ main ]
    paths:
     - '**.rs'
  workflow_dispatch:
jobs:
  release-ubuntu:
    name: Build for Linux
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      BUILD_TARGET: x86_64-unknown-linux-musl
      BINARY_NAME: fpm
    steps:
      - uses: actions/checkout@main
      - name: Build-musl
        uses: gmiam/rust-musl-action@master
        with:
          args: cargo build --target $BUILD_TARGET --release
      - uses: actions/upload-artifact@v2
        with:
          name: linux_musl_x86_64
          path: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}*
  release-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@v1
      - name: Run Build
        id: build-windows
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@master
        with:
          name: windows_x64_latest
          path: |
            target/release/fpm.exe
            README.md
            LICENSE
  release-macos:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@v1
      - name: Run Build
        id: build-macos
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@master
        with:
          name: macos_x64_latest
          path: |
            target/release/fpm
            README.md
            LICENSE